services:
  backend:
    build:
      context: ../..
      dockerfile: infra/monorepo-docker/Dockerfile
      target: backend-runtime
      args:
        NEXT_PUBLIC_PISSYKAKA_API: ${NEXT_PUBLIC_PISSYKAKA_API}
        NEXT_PUBLIC_EPDS_API: ${NEXT_PUBLIC_EPDS_API}
        NEXT_PUBLIC_DEFAULT_LIMIT: ${NEXT_PUBLIC_DEFAULT_LIMIT}
        NEXT_PUBLIC_FRONT_BASEURL: ${NEXT_PUBLIC_FRONT_BASEURL}
        NEXT_PUBLIC_PAGINATOR_MAX_ITEMS: ${NEXT_PUBLIC_PAGINATOR_MAX_ITEMS}
        NEXT_PUBLIC_CHAN_NAME: ${NEXT_PUBLIC_CHAN_NAME}
        NEXT_PUBLIC_FEATURE_FLAG_MODERKA: ${NEXT_PUBLIC_FEATURE_FLAG_MODERKA}
        METRICS_PASSWORD: ${METRICS_PASSWORD}
    env_file:
      - path: ${BACKEND_ENV_FILE:-../../packages/backend/.env}
        required: false
    environment:
      DATABASE_URL: ${BACKEND_DATABASE_URL:-file:./data/dev.db}
      # API_DEFAULT_LISTEN_PORT: ${BACKEND_PORT:-3000}
      API_DEFAULT_LISTEN_HOST: 0.0.0.0
      METRICS_PASSWORD: ${METRICS_PASSWORD}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - backend_data:/app/packages/backend/data
    restart: unless-stopped

  frontend:
    build:
      context: ../..
      dockerfile: infra/monorepo-docker/Dockerfile
      target: frontend-runtime
      args:
        NEXT_PUBLIC_PISSYKAKA_API: ${NEXT_PUBLIC_PISSYKAKA_API}
        NEXT_PUBLIC_EPDS_API: ${NEXT_PUBLIC_EPDS_API}
        NEXT_PUBLIC_DEFAULT_LIMIT: ${NEXT_PUBLIC_DEFAULT_LIMIT}
        NEXT_PUBLIC_FRONT_BASEURL: ${NEXT_PUBLIC_FRONT_BASEURL}
        NEXT_PUBLIC_PAGINATOR_MAX_ITEMS: ${NEXT_PUBLIC_PAGINATOR_MAX_ITEMS}
        NEXT_PUBLIC_CHAN_NAME: ${NEXT_PUBLIC_CHAN_NAME}
        NEXT_PUBLIC_FEATURE_FLAG_MODERKA: ${NEXT_PUBLIC_FEATURE_FLAG_MODERKA}
        METRICS_PASSWORD: ${METRICS_PASSWORD}
    env_file:
      - path: ${FRONTEND_ENV_FILE:-../../packages/frontend/.env.local}
        required: false
    environment:
      METRICS_PASSWORD: ${METRICS_PASSWORD}
    ports:
      - "${FRONTEND_PORT:-3040}:3040"
    depends_on:
      - backend
    restart: unless-stopped

  database:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_CHAN_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./:/app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 10

volumes:
  backend_data:
  mysql_data: