name: BACK Janitor checks code smell
run-name: BACK Janitor run triggered by ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          cd packages/backend
          npm i
          npm run build
